name = "Tsunami"
uuid = "36e41bbe-399b-4a86-8623-faa02b4c2ac8"
authors = "Carlo Lucibello"
version = "0.2.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
EnzymeCore = "f151be2c-9106-41f4-ab19-57ee4f262869"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MLDataDevices = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[weakdeps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"

[extensions]
TsunamiEnzymeExt = "Enzyme"

[compat]
BSON = "0.3.6"
ChainRulesCore = "1"
Compat = "4.16"
Crayons = "4"
Enzyme = "0.13.27"
EnzymeCore = "0.8.8"
Flux = "0.16"
Functors = "0.5.2"
GPUArraysCore = "0.1"
JLD2 = "0.5.10"
MLDataDevices = "1.6"
MLUtils = "0.4"
Optimisers = "0.4"
TensorBoardLogger = "0.1"
UnPack = "1"
Zygote = "0.6"
julia = "1.10"
