[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
Tsunami = "36e41bbe-399b-4a86-8623-faa02b4c2ac8"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"
